### PR TITLE
Add tests and documentation for non-default locales in Node

### PR DESCRIPTION
**Pull request by mtsknn**
This will be potentially confusing to many users without documentation. Node v12 is supported until 2022-04-30 ([source](https://nodejs.org/en/about/releases/)).

I took the instructions from my own SO answer: https://stackoverflow.com/a/56624712/1079869

### CODE REVIEW

**Review by xxczaki — APPROVED** [review]

**Comment by xxczaki** [comment]
Thanks once again!

**Comment by mtsknn** [comment]
@xxczaki, whoops, for some reason the unit test coverage of the `master` branch shows 0% now that this PR has been merged. 😅

**Comment by xxczaki** [comment]
@mtsknn Yeah, but the CLI still shows 100%, so that might be a bug with Coveralls. Nevertheless, I will look into that later today ;)

**Comment by mtsknn** [comment]
Looks like the reported coverage is back at 100%. 👍 May I ask what the issue was?

**Comment by xxczaki** [comment]
@mtsknn To best honest, I'm not sure 😆 I actually forgot about the broken coverage and after making a commit, everything has been fixed 😄

**Pull request merged**
